---
# NFT table and chain names
chineseroom_nft_table_filter: chineseroom_filter
chineseroom_nft_table_nat: chineseroom_nat

# Nginx configuration
chineseroom_nginx_root: /usr/share/nginx/html
chineseroom_user_map_file: "/home/{{ chineseroom_restricted_user }}/domainmap.txt"
chineseroom_domainmap_dir: /etc/chineseroom
chineseroom_domainmap_sandbox_dir: /etc/chineseroom/domainmap.sandbox.d

# Scripts and configuration paths
chineseroom_nginx_mapping_script: /usr/local/bin/regen-nginx-mappings.sh
chineseroom_nginx_conf_dir: /etc/nginx/conf.d
chineseroom_nginx_conf_trusted_dir: /etc/nginx/conf.trusted.d
chineseroom_nginx_conf_sandbox_dir: /etc/nginx/conf.sandbox.d
chineseroom_nginx_ssl_conf: "{{ chineseroom_nginx_conf_dir }}/chineseroom-ssl.conf"
chineseroom_letsencrypt_base: /etc/letsencrypt
