---
- name: Install prereqs
  # Make sure we have the libraries needed for Ansible to be able to install packages
  ansible.builtin.command: dnf install -y python3-libdnf5

- name: Create and configure chineseroom user
  import_tasks: user.yml
  tags:
  - chineseroom_user

- name: Install apps as the restricted user
  import_tasks: apps-user.yml
  tags:
  - chineseroom_apps_user

- name: Configure Let's Encrypt
  tags:
  - chineseroom_letsencrypt
  import_tasks: letsencrypt.yml

- name: Install and configure Nginx
  import_tasks: nginx.yml
  tags:
  - chineseroom_nginx

- name: Set up subdomain:port mappings from the restricted user
  import_tasks: usermapping.yml
  tags:
  - chineseroom_usermapping
