---
- name: Install required packages
  package:
    name:
      - nginx
    state: present

- name: Create nginx configuration for domain
  template:
    src: nginx-domain.conf.j2
    dest: "{{ chineseroom_nginx_conf_dir }}/{{ chineseroom_letsencrypt_domain }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: reload nginx

- name: Add connection upgrade map to nginx config
  copy:
    content: |
      # This is required to enable
      #   proxy_set_header   Connection $connection_upgrade;
      # which is required for WebSocket support
      map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
      }
    dest: "{{ chineseroom_nginx_conf_dir }}/connection-upgrade.conf"
    owner: root
    group: root
    mode: '0644'

- name: Configure firewall for HTTP and HTTPS
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - http
    - https

- name: Enable and start nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Allow nginx to connect to make outbound network connections
  # This is required for connecting to localhost too
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
