---
- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: User daemon-reload
  become: true
  become_user: "{{ chineseroom_restricted_user }}"
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user

- name: Enable claude-code-update.timer
  become: true
  become_user: "{{ chineseroom_restricted_user }}"
  ansible.builtin.systemd:
    name: claude-code-update.timer
    enabled: true
    state: started
    scope: user

- name: Enable openai-codex-update.timer
  become: true
  become_user: "{{ chineseroom_restricted_user }}"
  ansible.builtin.systemd:
    name: openai-codex-update.timer
    enabled: true
    state: started
    scope: user

- name: Enable pi-update.timer
  become: true
  become_user: "{{ chineseroom_restricted_user }}"
  ansible.builtin.systemd:
    name: pi-update.timer
    enabled: true
    state: started
    scope: user
